name: Deploy Backend Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Hostinger Stage
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /domains/demohandler.in/public_html/api/
          exclude: |
            **/.git*
            **/node_modules/**
            .env
